--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user (
    id integer NOT NULL,
    created_at timestamp without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    last_login timestamp without time zone,
    password character varying(255) NOT NULL
);


--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_phones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_phones (
    user_id integer NOT NULL,
    area_code integer,
    country_code character varying(255),
    number integer
);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: tb_user uk_4vih17mube9j7cqyjlfbcrk4m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT uk_4vih17mube9j7cqyjlfbcrk4m UNIQUE (email);


--
-- Name: user_phones fknl3o1am4wq2ejlcgm8mld4aek; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_phones
    ADD CONSTRAINT fknl3o1am4wq2ejlcgm8mld4aek FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- PostgreSQL database dump complete
--

